backend:
  name: github
  repo: abelabelabelabel/abelabelabelabel.github.io
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://abelvanoosterwijk.com
collections:
  - name: 'publicaties'
    label: 'Publicaties'
    folder: 'content/publicaties'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Is Draft?', name: 'draft', widget: 'boolean' }
      - { label: 'Subtitle', name: 'summary', widget: 'markdown' }
      - { label: 'URL', name: 'link', widget: 'string' }
